### ISSUE TITLE
Subprojects using root's version fields

### ISSUE THREAD

**Issue by cengizkandemir** [rockerhieu/Versionberg#2]
I have an app and a library located at different git repositories. The lib is git submodule and a sub gradle project, both using Versionberg. When the gradle is invoked from the app's top-level for compilation, the version fields are propagated to subproject.

For example, I have
- Project Root
--- app (assume version as 1.0.20.XXXXXXX)
--- someLib (git module, assume version as 1.0.50.YYYYYYY)

when assembleDebug is invoked, the following output files are produced

app-1.0.20.XXXXXXX.apk
someLib-1.0.20.XXXXXXX.aar

The expected output, however, should be

app-1.0.20.XXXXXXX.apk
someLib-1.0.50.YYYYYYY.aar

Not sure, if this is a bug, or an expected behavior. Is there a way to "clear" the state of Versionberg.

Thank you.

**Comment by rockerhieu** [comment]
@cengizkandemir can you share your build scripts of the two project? Or at least show me how did you configure versionberg in the 2 modules.

**Comment by rockerhieu** [comment]
Gotcha, so you want the lib project to use git commit count of the submodule repository, don't you? This is not supported yet.

**Comment by cengizkandemir** [comment]
Issued a pull request just now. I'd appreciate if you review it, and release a new version if it's acceptable.

**Comment by rockerhieu** [comment]
Supported in v1.0.1

**Comment by rockerhieu** [comment]
v1.0.1 is live now
