### ISSUE TITLE
Casting exception

### ISSUE THREAD

**Issue by cengizkandemir** [rockerhieu/Versionberg#4]
I am having the following error when I use _io.github.rockerhieu:versionberg:1.0.1_

> Cannot cast object 'null' with class 'null' to class 'int'. Try 'java.lang.Integer' instead

This doesn't seem to be the case if I compile the plugin from the source, and declare it as the dependency. Is _io.github.rockerhieu:versionberg:1.0.1_ the latest version?

For the record, the same gradle script runs well if I use _io.github.rockerhieu:versionberg:1.0.0_ and comment out the `gitDir` attribute.

**Comment by rockerhieu** [comment]
What does your `gitDir` look like?

**Comment by rockerhieu** [comment]
This is an example of `gitDir` usage:

```
versionberg {
    major 1
    minor 0
    patch 10
    nameTemplate '${major}.${minor}.${commitSha}.${new Date().format("ddMMyyyy")}-SNAPSHOT'
    codeTemplate '(((${major} * 100) + ${minor}) * 100) * 100000 + ${build}'
    gitDir new File("/Users/myuser/Development/Versionberg/.git")
}
```

**Comment by cengizkandemir** [comment]
`gitDir "${project.projectDir.absolutePath}/.."`

But this might not be the issue. Giving absolute path, e.g., "/home/user/\<path-to-git-repo\>" doesn't seem to solve this problem either.

As I said, compiling from sources, and giving dependency to the local jar file doesn't cause this problem. Complete Versionberg field:

```
versionberg {
    gitDir "${project.projectDir.absolutePath}/.."
    major 0
    minor 0
    patch 0
    nameTemplate '${major}.${minor}.${patch}.${commitCount}.${commitSha}'
    codeTemplate '(((${major} * 100) + ${minor}) * 100) * 100000 + ${build}'
}
```

**Comment by cengizkandemir** [comment]
I just realized that you are using File type. But changing it to point a file with a .git path doesn't seem to help.

Also, it appears that I was using an older local version. I just re-fetched the head and the problem exists even when I compile from the source.

Compiling with the following field produces a different error:

```
versionberg {
    major 0
    minor 0
    patch 0
    nameTemplate '${major}.${minor}.${patch}.${commitCount}.${commitSha}'
    codeTemplate '(((${major} * 100) + ${minor}) * 100) * 100000 + ${build}'
    gitDir new File("\<path-to-some-git-repo/.git\>")
}
```

> Ambiguous method overloading for method java.lang.Integer#plus.
>   Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
>         [class java.lang.Character]
>         [class java.lang.String]
>         [class java.lang.Number]

Not sure if I am doing something wrong, but the problem occurs somewhere around, I think, `getCode()`.

Commenting out  `versionCode versionberg.code` solves the compilation issue.

**Comment by rockerhieu** [comment]
@cengizkandemir can you try running this command line?
```
./gradlew versionbergInfo --refresh-dependencies
```

**Comment by rockerhieu** [comment]
I think I can reproduce the same issue now. Talking a look now.

**Comment by rockerhieu** [comment]
Can you try `1.0.2-SNAPSHOT`?

```gradle
buildscript {
    repositories {
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
    dependencies {
        classpath 'io.github.rockerhieu:versionberg:1.0.2-SNAPSHOT'
    }
}

apply plugin: "io.github.rockerhieu.versionberg"
```

If it work then I will release 1.0.2.

**Comment by cengizkandemir** [comment]
I'll check it next monday.

**Comment by rockerhieu** [comment]
@cengizkandemir did you check it?

**Comment by cengizkandemir** [comment]
This seems to work. What is the difference between these two releases?

**Comment by rockerhieu** [comment]
There was a bug when initializing `Versionberg` extension. Cool, let me publish `1.0.2`.

**Comment by rockerhieu** [comment]
Here it is https://github.com/rockerhieu/Versionberg/releases/tag/releases%2Fv1.0.2
