### ISSUE TITLE
Issue with large number due to shell.evaluate under Eval.me

### ISSUE THREAD

**Issue by thelittlefireman** [rockerhieu/Versionberg#5]
https://github.com/rockerhieu/Versionberg/blob/bf2e9f0f81d8caffd11960839f2d02d1cddb10a2/versionberg/src/main/groovy/io/github/rockerhieu/versionberg/Versionberg.groovy#L64

i have huge issue with this script : 
```
apply plugin: 'io.github.rockerhieu.versionberg'
versionberg {
    // Increase when you make incompatible API changes (default value is 0)
    major 25
    minor 1
        nameTemplate 'V01.${major}${minor}-${commitSha}-${new Date().format("dd_MM_yyyy")}'
    codeTemplate '${major}*(100000000) + ${minor}*(10000) +${build}'
}
```

it always return negative value due tu integer overflow

after some reseach and test on https://groovyconsole.appspot.com/ 

the codeTemplate is working when you add L at the end of large number : 
`'25*(100000000) + 1*(10000) +1198'` = -1794956098
`'25*(100000000L) + 1*(10000L) +1198'` = 2500011198

i try : ` codeTemplate '${major}*(100000000L) + ${minor}*(10000L) +${build}'` but doesn't work i still got negative value. 😕 

Any help, or ideas ? 

thanks 
thomas

**Comment by rockerhieu** [comment]
How about reducing `100000000` and `10000`? I could use Long to hold the value of `versionberg.code` but it won't be compatible with Android's versionCode.

**Comment by thelittlefireman** [comment]
Thanks you for your answer. I can't because  I already publish apk with a high versionCode. I think the real question is why "codeTemplate '${major}*(100000000) + ${minor}*(10000) +${build}'" return a negative number ? because 25 * 100000000+1 * 10000 + 1197 < 2,147,483,647 (Integer Max value)

**Comment by rockerhieu** [comment]
That's interesting indeed, let me check.

**Comment by rockerhieu** [comment]
@thelittlefireman have you tried to execute this on the groovy console?
```groovy
print((int) 2500011198)
```

And 2500011198 is clearly greater than Integer.MAX_VALUE.
